#python3 main.py --fl fedavg --dataset fairFashionMNIST --varying_disc 0.1
#python3 main.py --fl oracle --dataset fairFashionMNIST --varying_disc 0.1
python3 main.py --fl fedavg --dataset fairFashionMNIST --varying_disc 0.2
python3 main.py --fl oracle --dataset fairFashionMNIST --varying_disc 0.2
python3 main.py --fl fedavg --dataset fairFashionMNIST --varying_disc 0.3
python3 main.py --fl oracle --dataset fairFashionMNIST --varying_disc 0.3
python3 main.py --fl fedavg --dataset fairFashionMNIST --varying_disc 0.4
python3 main.py --fl oracle --dataset fairFashionMNIST --varying_disc 0.4
#python3 main.py --fl fedavg --dataset fairFashionMNIST --varying_disc 0.5
#python3 main.py --fl oracle --dataset fairFashionMNIST --varying_disc 0.5
python3 main.py --fl fedavg --dataset fairFashionMNIST --varying_disc 0.6
python3 main.py --fl oracle --dataset fairFashionMNIST --varying_disc 0.6
python3 main.py --fl fedavg --dataset fairFashionMNIST --varying_disc 0.7
python3 main.py --fl oracle --dataset fairFashionMNIST --varying_disc 0.7
python3 main.py --fl fedavg --dataset fairFashionMNIST --varying_disc 0.8
python3 main.py --fl oracle --dataset fairFashionMNIST --varying_disc 0.8
python3 main.py --fl fedavg --dataset fairFashionMNIST --varying_disc 0.9
python3 main.py --fl oracle --dataset fairFashionMNIST --varying_disc 0.9
python3 main.py --fl fedavg --dataset fairFashionMNIST --varying_disc 1.0
python3 main.py --fl oracle --dataset fairFashionMNIST --varying_disc 1.0
